server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: "sa"
    password: "root"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  application:
    name: "Person management system"
    version: 1.0
    description: "
      My test project with Spring Boot. 
      Used technologies: 
        Spring Web, 
        Spring Data JPA, 
        Swagger, 
        H2"
springdoc:
  contact:
    name: "Bogdan Zaranik"
    email: "zaranikbz@gmail.com"
  swagger-ui:
    path: "/swagger"
