server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:test"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: "TodoApp"
    version: 1.0
    description: "
      My the pet project with Spring Boot. 
      Used technologies: 
        Spring Web, 
        Spring Data JPA, 
        Swagger, 
        H2"
springdoc:
  contact:
    name: "Bogdan Zaranik"
    email: "zaranikbz@gmail.com"
